# Generated by Django 2.0.3 on 2020-07-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(max_length=64)),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CityObjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=64)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(max_length=128)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CityObjectsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sha256', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CityObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cityobjectphoto',
            name='contributing_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityobjects_api.CityObjectsUser'),
        ),
        migrations.AddField(
            model_name='cityobject',
            name='object_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityobjects_api.CityObjectPhoto'),
        ),
        migrations.AddField(
            model_name='cityobject',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cityobjects_api.CityObjectType'),
        ),
    ]
